POST http://localhost:8080/api/chat
Content-Type: application/json

{
  "title": "title",
  "lastActivity": "1605283200000",
  "llmId": "1"
}

### Get all chats
GET http://localhost:8080/api/chat


### Put a chat
PUT http://localhost:8080/api/chat
Content-Type: application/json

{
  "id": "0",
  "title": "title24",
  "lastActivity": "1704283240000",
  "llmId": "1"
}

### Delete a chat
DELETE http://localhost:8080/api/chat/5

### Get a chat by id
GET http://localhost:8080/api/chat/0
