package fr.esiee.app.services;

import dev.langchain4j.data.message.AiMessage;
import dev.langchain4j.data.message.ChatMessage;
import dev.langchain4j.data.message.ChatMessageType;
import dev.langchain4j.data.message.SystemMessage;
import dev.langchain4j.data.message.UserMessage;
import dev.langchain4j.memory.ChatMemory;
import dev.langchain4j.memory.chat.MessageWindowChatMemory;
import dev.langchain4j.model.ollama.OllamaChatModel;
import dev.langchain4j.service.AiServices;
import fr.esiee.app.db.DbManager;
import fr.esiee.app.utils.ErrorUtils;
import fr.esiee.app.utils.CompileAndExecUtils;
import fr.esiee.app.config.LLMConfig;
import fr.esiee.app.db.entities.AuthorType;
import fr.esiee.app.db.entities.LLM;
import fr.esiee.app.db.entities.Prompt;
import fr.esiee.app.exception.RestApiException;
import io.helidon.common.context.Contexts;
import io.helidon.http.Status;
import io.helidon.http.sse.SseEvent;
import io.helidon.webserver.http.*;
import io.helidon.webserver.sse.SseSink;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.ws.rs.Consumes;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import java.io.IOException;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.concurrent.ExecutionException;

@Tag(name = "Generator", description = "endpoints to use generator")
@Path("/api/gen")
public class GeneratorService implements HttpService {

  private static final Logger LOGGER = LoggerFactory.getLogger(GeneratorService.class);
  private static final String SYSTEM_ERR_MESSAGE = "Here are the compilation errors, correct them.";
  private final DbManager dbService;
  private final LLMConfig llmConfig;
  private final int NB_ATTEMPTS = 3;
  private final int MAX_MEMORY_PROMPTS = 30;

  private LLM curLLM;
  private OllamaChatModel model;
  private Assistant assistant;
  private Prompt pendingPrompt;


  private interface Assistant {
    String chat(@dev.langchain4j.service.UserMessage String userMessage);
  }

  private record SourceCode(String code, boolean compiled) {}
  private record LLMResponse(LLMResponseStatus status, String content, Prompt prompt) {
    public static LLMResponse generating(String content) {
      return new LLMResponse(LLMResponseStatus.GENERATING, content, null);
    }
    public static LLMResponse error(Prompt prompt) {
      return new LLMResponse(LLMResponseStatus.ERROR, null, prompt);
    }
    public static LLMResponse done(Prompt prompt) {
      return new LLMResponse(LLMResponseStatus.SUCCESS, null, prompt);
    }
    public static LLMResponse finish() {
      return new LLMResponse(LLMResponseStatus.FINISH, null, null);
    }
  }
  private enum LLMResponseStatus { GENERATING, ERROR, SUCCESS, FINISH }

  public GeneratorService() {
    this.dbService = Contexts.globalContext().get(DbManager.class).orElseThrow(() -> new NoSuchElementException("DbManager not found."));
    this.llmConfig = Contexts.globalContext().get(LLMConfig.class).orElse(LLMConfig.defaultConfig());
  }

  @Override
  public void routing(HttpRules rules) {
    rules.post("/class", Handler.create(Prompt.class, this::receivePrompt))
            .get("/stream", this::streamLLMResponse)
            .post("/exec", Handler.create(Integer.class, this::executeClass));
  }

  @POST
  @Path("/class")
  @Operation(summary = "generate a class", description = "Retrieves a class generated by llm")
  @Consumes("application/json")
  @ApiResponse(content = @Content(mediaType = "application/json", schema = @Schema(implementation = Prompt.class)),
          responseCode = "200", description = "Class generated successfully")
  public void receivePrompt(Prompt prompt, @Parameter(hidden = true) ServerResponse res) {
    Objects.requireNonNull(prompt);
    Objects.requireNonNull(res);
    if(pendingPrompt != null) {
      LOGGER.error("Front is trying to send a prompt, but a prompt is already being processed.");
      ErrorUtils.send(res, Status.NOT_ACCEPTABLE_406, "A prompt is already being processed.");
      return;
    }
    pendingPrompt = prompt;
    res.status(Status.OK_200).send("Prompt received successfully.");
  }

  public void streamLLMResponse(ServerRequest req, ServerResponse res) {
    try (var sseSink = res.sink(SseSink.TYPE)) {
      if(pendingPrompt == null) {
        LOGGER.error("Front is trying to stream a response, but no prompt is pending.");
        sseSink.emit(SseEvent.create(LLMResponse.finish()));
        sseSink.close();
        return;
      }
      var chat = dbService.getChatById(pendingPrompt.chatId());
      var newLLM = dbService.getLLMById(chat.llmId());
      dbService.insertPrompt(pendingPrompt);

      SourceCode generatedCode;
      try {
        generatedCode = generateClassFromLLM(newLLM, chat.id(), pendingPrompt.message(), sseSink);
        LOGGER.info("Class generated successfully.");
        var aiPrompt = new Prompt(0, generatedCode.code, AuthorType.AI, chat.id(), generatedCode.compiled);
        dbService.insertPrompt(aiPrompt);
        var registeredPrompt = dbService.getPromptByPromptInfo(aiPrompt);
        sseSink.emit(SseEvent.create(LLMResponse.done(registeredPrompt)));
      } catch (IOException | InterruptedException | ExecutionException e) {
        LOGGER.error("Error occurred while generating and streaming response to front :", e);
        sseSink.emit(SseEvent.create(LLMResponse.error(registerErrorPrompt("Error while generating class.", chat.id()))));
      } finally {
        sseSink.close();
        pendingPrompt = null;
      }
    }
  }

  @POST
  @Path("/exec")
  @Operation(summary = "Execute a class", description = "Executes a java class and returns the output")
  @Consumes("text/plain")
  @ApiResponse(content = @Content(mediaType = "text/plain"), responseCode = "200", description = "Class execution output")
  public void executeClass(int promptId, @Parameter(hidden = true) ServerResponse res) {
    var prompt = dbService.getPromptById(promptId);
    if (!prompt.compile()) {
      LOGGER.error("Front is trying to execute a class that does not compile");
      ErrorUtils.send(res, Status.NOT_ACCEPTABLE_406, "Prompt not supposed to be compiled.");
      return;
    }
    String output;
    try {
      LOGGER.info("Executing class, promptId : {}", promptId);
      output = CompileAndExecUtils.processText(prompt.message(), CompileAndExecUtils.Operation.EXECUTE);
    } catch (IOException | InterruptedException | ExecutionException e) { // Catch is necessary because whe are in a BiConsumer lambda
      throw new RestApiException(e);
    }
    res.status(Status.OK_200).send(output);
  }

  private Prompt registerErrorPrompt(String errorMessage, int chatId) {
    var prompt = new Prompt(0, errorMessage, AuthorType.SYSTEM, chatId, false);
    dbService.insertPrompt(prompt);
    return dbService.getPromptByPromptInfo(prompt);
  }

  private SourceCode generateClassFromLLM(LLM llm, int chatId, String requestText, SseSink sseSink)
          throws IOException, ExecutionException, InterruptedException {
    Objects.requireNonNull(llm);
    Objects.requireNonNull(requestText);

    if (llm != curLLM || model == null || assistant == null) {
      updateModelSettings(llm, chatId);
      curLLM = llm;
    }

    String errorsText = null;
    String code = null;
    for (int attempt = 1; attempt <= NB_ATTEMPTS; attempt++) {
      LOGGER.info("Attempting to generate class (attempt {}/{}).", attempt, NB_ATTEMPTS);
      sseSink.emit(SseEvent.create(LLMResponse.generating("Attempting to generate class (attempt " + attempt + "/" + NB_ATTEMPTS + ").")));

      String answer;
      try{
        answer = assistant.chat(attempt == 1 ? requestText : errorsText);
      } catch (RuntimeException e) {
        throw new IOException("Error while asking assistant to generate response.", e.getCause());
      }

      code = CompileAndExecUtils.extractCode(answer);
      LOGGER.info("Code extracted from response.");
      sseSink.emit(SseEvent.create(LLMResponse.generating("Code extracted from response.")));

      var errors = CompileAndExecUtils.processText(code, CompileAndExecUtils.Operation.COMPILE);

      if (errors.isEmpty()) {
        LOGGER.info("No errors found in generated code.");
        sseSink.emit(SseEvent.create(LLMResponse.generating("No errors found in generated code.")));
        return new SourceCode(code, true);
      } else {
        LOGGER.info("Errors found in generated code:\n{}", errors);
        sseSink.emit(SseEvent.create(LLMResponse.generating("Errors found in generated code.")));
        errorsText = SYSTEM_ERR_MESSAGE + errors;
      }
    }
    return new SourceCode(code, false);
  }

  private void updateModelSettings(LLM llm, int chatId) {
    var chatMemory = MessageWindowChatMemory.withMaxMessages(MAX_MEMORY_PROMPTS);
    updateMemoryWithPreviousPrompts(chatMemory, chatId);
    model = OllamaChatModel.builder()
            .baseUrl(llmConfig.baseUrl())
            .modelName(llm.model())
            .temperature(llm.temp())
            .seed(llm.seed())
            .build();

    assistant = AiServices.builder(Assistant.class)
            .chatLanguageModel(model)
            .systemMessageProvider(_ -> llm.systemPrompt())
            .chatMemory(chatMemory)
            .build();
  }

  private void updateMemoryWithPreviousPrompts(ChatMemory chatMemory, int chatId) {
    var prevPrompts = dbService.getPromptsByChatId(chatId);
    prevPrompts
            .forEach(prompt -> {
              ChatMessageType type = ChatMessageType.valueOf(prompt.authorType().name());
              if (type == ChatMessageType.USER) {
                chatMemory.add(new UserMessage(prompt.message()));
              } else if (type == ChatMessageType.AI) {
                chatMemory.add(new AiMessage(prompt.message()));
              } else if (type == ChatMessageType.SYSTEM) {
                chatMemory.add(new SystemMessage(prompt.message()));
              }
            });
  }
}
