package fr.esiee.app.services;

import dev.langchain4j.memory.chat.MessageWindowChatMemory;
import dev.langchain4j.model.ollama.OllamaChatModel;
import dev.langchain4j.service.AiServices;
import dev.langchain4j.service.SystemMessage;
import dev.langchain4j.service.UserMessage;
import dev.langchain4j.service.V;
import fr.esiee.app.errors.ErrorUtils;
import fr.esiee.app.config.LLMProviderConfig;
import fr.esiee.app.db.entities.AuthorType;
import fr.esiee.app.db.entities.LLM;
import fr.esiee.app.db.entities.Prompt;
import io.helidon.common.context.Contexts;
import io.helidon.http.Status;
import io.helidon.webserver.http.Handler;
import io.helidon.webserver.http.HttpRules;
import io.helidon.webserver.http.HttpService;
import io.helidon.webserver.http.ServerResponse;
import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.info.Info;
import io.swagger.v3.oas.annotations.servers.Server;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.ws.rs.POST;
import javax.ws.rs.Path;
import java.io.IOException;
import java.util.Objects;

@OpenAPIDefinition(
        info = @Info(
                title = "GPT for dev API services",
                description = "Services for manipulating chats, prompts and llms"
        ),
        servers = {
                @Server(
                        description = "localhost",
                        url = "http://localhost:8080")
        }
)
@Tag(name = "Generator", description = "endpoints to use generator")
@Path("/api/gen")
public class GeneratorService implements HttpService {

  private static final Logger LOGGER = LoggerFactory.getLogger(GeneratorService.class);

  private static final String SYSTEM_ERR_MESSAGE_2 = """
  Here are the compilation errors, correct them.""";
  private static final String USER_ERR_MESSAGE = "There are compilation errors in the generated class : ";
  private final DbService dbService;
  private final LLMProviderConfig llmConfig;
  private final int NB_ATTEMPTS = 3;
  private final int MAX_MEMORY_PROMPTS = 30;

  private LLM curLLM;
  private OllamaChatModel model;
  private Assistant assistant;

  public GeneratorService() {
    this.dbService = Contexts.globalContext().get(DbService.class).orElse(DbService.getInstance());
    this.llmConfig = Contexts.globalContext().get(LLMProviderConfig.class).orElse(LLMProviderConfig.defaultConfig());
  }

  @Override
  public void routing(HttpRules rules) {
    rules.post("/class", Handler.create(Prompt.class, this::generateClass))
            .post("/exec", Handler.create(Integer.class, this::executeClass));
  }

  @POST
  @javax.ws.rs.Path("/class")
  @Operation(summary = "generate a class", description = "Retrieves a class generated by llm")
  public void generateClass(Prompt prompt, @Parameter(hidden = true) ServerResponse res) {
    var chat = dbService.getChatById(prompt.chatId());
    var newLLM = dbService.getLLMById(chat.llmId());
    dbService.insertPrompt(prompt);

    String generatedClass = "Error generating class.";
    var compile = false;
    try {
      generatedClass = generateClassFromLLM(newLLM, prompt.message());
      LOGGER.info("Class generated successfully.");
      compile = true;
    } catch (IOException | RuntimeException e) {
      LOGGER.error("Error during class generation.");
    }

    var aiPrompt = new Prompt(0, generatedClass, AuthorType.LLM, chat.id(), compile);
    dbService.insertPrompt(aiPrompt);
    var realPrompt = dbService.getPromptByPromptInfo(aiPrompt);
    res.send(realPrompt);
  }

  @POST
  @javax.ws.rs.Path("/exec")
  @Operation(summary = "Execute a class", description = "Executes a java class and returns the output")
  public void executeClass(int promtId, @Parameter(hidden = true) ServerResponse res) {
    var prompt = dbService.getPromptById(promtId);
    if (!prompt.compile()) {
      ErrorUtils.send(res, Status.INTERNAL_SERVER_ERROR_500, "Prompt not supposed to be compiled.");
      return;
    }

    String output;
    try {
      LOGGER.info("Executing class ...");
      output = CompileService.compileAndExecuteText(prompt.message());
    } catch (IOException | InterruptedException e) {
      output = "An error occurred while executing class.";
      LOGGER.error("{}", output);
    }
    res.send(output);
  }

  private String generateClassFromLLM(LLM llm, String requestText) throws IOException {
    Objects.requireNonNull(llm);
    Objects.requireNonNull(requestText);

    if (llm != curLLM || model == null || assistant == null) {
      updateModelSettings(llm);
      curLLM = llm;
    }

    String errorsText = null;
    for (int attempt = 0; attempt < NB_ATTEMPTS; attempt++) {
      LOGGER.info("Attemp n° {} to generate class ...", attempt);

      var answer = assistant.chat(llm.systemPrompt(), attempt == 0 ? requestText : errorsText);
      LOGGER.info("Assistant made a response.");

      String code = CompileService.extractCode(answer);
      LOGGER.info("Code extracted from response.");

      var errors = CompileService.processAndCompileText(code);

      if (errors.isEmpty()) {
        LOGGER.info("No errors found in generated code.");
        return code;
      } else {
        LOGGER.error("Errors found in generated code.");
        errorsText = SYSTEM_ERR_MESSAGE_2 + String.join("\n", errors);
      }
    }
    throw new RuntimeException(USER_ERR_MESSAGE + errorsText);
  }

  private interface Assistant {
    @SystemMessage("{{answerInstructions}}")
    String chat(@V("answerInstructions") String answerInstructions, @UserMessage String userMessage);
  }

  private void updateModelSettings(LLM llm) {
    var chatMemory = MessageWindowChatMemory.withMaxMessages(MAX_MEMORY_PROMPTS);
    model = OllamaChatModel.builder()
            .baseUrl(llmConfig.baseUrl())
            .modelName(llm.model())
            .temperature(llm.temp())
            .seed(llm.seed())
            .build();

    assistant = AiServices.builder(Assistant.class)
            .chatLanguageModel(model)
            .chatMemory(chatMemory)
            .build();
  }
}
