server:
  port: 8080
  host: 0.0.0.0

app:
  greeting: "Hello"

db:
  source: jdbc
  connection:
    url: "jdbc:h2:./data/db;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE"
    username: "sa"
    password:
    poolName: h2
    initializationFailTimeout: -1
    connectionTimeout: 2000
  init-schema: "false"
  init-data: "false"

  statements:

    # Table creation
    create-llm: "CREATE TABLE LLM (id INTEGER NOT NULL PRIMARY KEY, name VARCHAR(64) NOT NULL)"
    create-chat: "CREATE TABLE Chat (id INTEGER NOT NULL PRIMARY KEY, title VARCHAR(128) NOT NULL)"
    create-prompt: "CREATE TABLE Prompt (id INTEGER NOT NULL PRIMARY KEY, user_message VARCHAR(256) NOT NULL, llm_response VARCHAR(256) NOT NULL, id_llm INTEGER NOT NULL REFERENCES LLM(id), id_chat INTEGER NOT NULL REFERENCES Chat(id))"

    # Insert statements
    insert-llm: "INSERT INTO LLM(id, name) VALUES(?, ?)"
    insert-chat: "INSERT INTO Chat(id, title) VALUES(?, ?)"
    insert-prompt: "INSERT INTO Prompt(id, user_message, llm_response, id_llm, id_chat) VALUES(?, ?, ?, ?, ?)"

    # Select all entries
    select-all-llms: "SELECT id, name FROM LLM"
    select-all-chats: "SELECT id, title FROM Chat"
    select-all-prompts: "SELECT id, user_message, llm_response, id_llm, id_chat FROM Prompt"

    # Select entries by id
    select-llm-by-id: "SELECT id, name FROM LLM WHERE id = :id"
    select-chat-by-id: "SELECT id, title FROM Chat WHERE id = :id"
    select-prompt-by-id: "SELECT id, user_message, llm_response, id_llm, id_chat FROM Prompt WHERE id = :id"

    # Retrieve LLM and Chat from Prompt (through foreign keys)
    retrieve-llm-from-prompt: "SELECT LLM.id, LLM.name FROM LLM JOIN Prompt ON LLM.id = Prompt.id_llm WHERE Prompt.id = :promptId"
    retrieve-chat-from-prompt: "SELECT Chat.id, Chat.title FROM Chat JOIN Prompt ON Chat.id = Prompt.id_chat WHERE Prompt.id = :promptId"

    # Update statements
    update-llm-by-id: "UPDATE LLM SET name = :name WHERE id = :id"
    update-chat-by-id: "UPDATE Chat SET title = :title WHERE id = :id"
    update-prompt-by-id: "UPDATE Prompt SET user_message = :userMessage, llm_response = :llmResponse, id_llm = :llmId, id_chat = :chatId WHERE id = :id"

    # Delete statements (single entry)
    delete-llm-by-id: "DELETE FROM LLM WHERE id = :id"
    delete-chat-by-id: "DELETE FROM Chat WHERE id = :id"
    delete-prompt-by-id: "DELETE FROM Prompt WHERE id = :id"

    # Delete all entries
    delete-all-llms: "DELETE FROM LLM"
    delete-all-chats: "DELETE FROM Chat"
    delete-all-prompts: "DELETE FROM Prompt"

    # Get prompts by chat id
    select-prompts-by-chat-id: "SELECT id, user_message, llm_response, id_chat, id_llm FROM prompt WHERE id_chat = :id_chat"
